### PR TITLE
Merge master into dev

### PR DESCRIPTION
**Pull request by nezorflame**
Bump `dev` branch.

### CODE REVIEW

**Comment by fiorix** [comment]
Is this just a sync from master->dev?

**Comment by nezorflame** [comment]
@fiorix yep

**Comment by nezorflame** [comment]
That Travis...fails on building for tip:
`The command "go get -d -v golang.org/x/tools/cmd/cover" failed and exited with 1 during .`

**Comment by nezorflame** [comment]
@fiorix bump this as well :)

**Comment by fiorix** [comment]
Yup, looked at it last night but it was still running the tests. LGTM now :)

**Pull request merged**
