### PR TITLE
Handle Optional params

### PR DESCRIPTION
**Pull request by McSwitch**
Added sending/receiving TLV field support to resolve issue #24

### CODE REVIEW

**Comment by fiorix** [comment]
I'm mostly happy with this code, except the parts that stutters: pdutlv.TLVMap -> pdutlv.Map. Surprised if golint doesn't complain about it.

It'd be great if you could 1) clean up those names, and 2) squash your commits into a single commit so I can rebase and merge

None of them are really blocking. I kinda care about what the code does and looks like, but if others are happy to land this I am ok too. The second part I could also do from here but I'd rather simply rebase and merge a single commit from you directly.

**Comment by fiorix** [comment]
Hey @McSwitch let me know if you need any help.

**Comment by McSwitch** [comment]
@nezorflame and @fiorix, I have made the requested changes. But TravisCI build are extremely slow today and as a result are running into timeout issues (see build 115 and 116). I will try the build again tomorrow.

**Comment by McSwitch** [comment]
@nezorflame and @fiorix, TravisCI is a lot faster today so I have rebuilt the commit today without any timeout issues. Please review changes, let me know if there is anything else required for the merge.

**Comment by fiorix** [comment]
💯 

Thank you!

**Pull request merged**
